//Practicas bootstrap layout

import type { Metadata } from "next";
import '../../../node_modules/bootstrap/dist/css/bootstrap.min.css';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body >
        <div className="container-fluid">
          <div className="row justify-content-center">
            <div className="col-8">
              <p className="h1">
                Inicio de Sintaxis y codigo para ejemplos de Next.js
              </p>
            </div>
          </div>
        {children}
        </div>
      </body>
    </html>
  );
}
