//Main layout 
//Este layout funje como principal y carece de pagina page por la configuracion en la carpeta Practicas bootstrap

import type { Metadata } from "next";

/* Importacion de styles vamos a poner todo lo general dentro de este layout */
import '../../styles/global.css'
import { Providers } from "./Providers";
/*Fin  importacion de styles vamos a poner todo lo general dentro de este layout */

export const metadata: Metadata = {
  title: "Sintaxis basica para Next y Typescript",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark text-foreground bg-background">
        {children}
   {/*      <>
        <layout>
          <Navbar>
            <button>agregar incidencia</button>
            <modal>
              <form action="">
                <input type="text" />
                <input type="text" />
                <input type="text" />
                <input type="text" />
              </form>
            </modal>
          </Navbar>
          <Page>
            <Dashboardcontainer>
              etc...
            </Dashboardcontainer>
          </Page>
        </layout>
        </> */}
      </body>
    </html>

    
  );
}
