//Main layout 
//Este layout funje como principal y carece de pagina page por la configuracion en la carpeta Practicas bootstrap

import type { Metadata } from "next";
import { Providers } from "../Providers";
import { div } from "framer-motion/client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <div>
      <Providers>
        {children}
      </Providers>
    </div>
  );
}
